import { useQuery } from '@tanstack/react-query';
import { Alert, Card, Col, Empty, List, Row, Space, Statistic, Tag, Typography } from 'antd';
import ReactECharts from 'echarts-for-react';

import { getMockAnalytics } from '../api/analytics';

const { Title, Text } = Typography;

export function AnalyticsPage() {
  const query = useQuery({
    queryKey: ['analytics', 'mock'],
    queryFn: getMockAnalytics,
  });

  if (query.isLoading) return <Card loading />;
  if (query.error) return <Alert type="error" message={(query.error as Error).message} />;
  const data = query.data;
  if (!data) return <Empty description="No analytics data" />;

  const option = {
    tooltip: { trigger: 'axis' },
    legend: { data: ['CTR', 'CVR', 'Completion'] },
    grid: { left: 40, right: 24, top: 48, bottom: 72 },
    xAxis: {
      type: 'category',
      data: data.metrics.map((item) => item.factor),
      axisLabel: { interval: 0, rotate: 20 },
    },
    yAxis: {
      type: 'value',
      axisLabel: {
        formatter: (value: number) => `${Math.round(value * 100)}%`,
      },
    },
    series: [
      {
        name: 'CTR',
        type: 'bar',
        data: data.metrics.map((item) => item.ctr),
      },
      {
        name: 'CVR',
        type: 'bar',
        data: data.metrics.map((item) => item.cvr),
      },
      {
        name: 'Completion',
        type: 'bar',
        data: data.metrics.map((item) => item.completion_rate),
      },
    ],
  };

  const bestCompletion = [...data.metrics].sort(
    (a, b) => b.completion_rate - a.completion_rate,
  )[0];

  return (
    <Space direction="vertical" size="large" style={{ width: '100%' }}>
      <div>
        <Title level={3} style={{ marginBottom: 4 }}>
          Analytics
        </Title>
        <Text type="secondary">Mock factor attribution generated by the Python Agent.</Text>
      </div>

      <Row gutter={[16, 16]}>
        <Col xs={24} md={8}>
          <Card>
            <Statistic
              title="Best completion factor"
              value={bestCompletion?.factor ?? '-'}
              valueStyle={{ fontSize: 18 }}
            />
          </Card>
        </Col>
        <Col xs={24} md={8}>
          <Card>
            <Statistic
              title="Avg CTR"
              value={
                data.metrics.reduce((sum, item) => sum + item.ctr, 0) / Math.max(data.metrics.length, 1)
              }
              precision={3}
            />
          </Card>
        </Col>
        <Col xs={24} md={8}>
          <Card>
            <Statistic
              title="Agent trace"
              value={data.trace?.[0]?.stage ?? 'agent.analytics.mock'}
              valueStyle={{ fontSize: 18 }}
            />
          </Card>
        </Col>
      </Row>

      <Card title="Factor x conversion effect">
        <ReactECharts option={option} style={{ height: 420 }} />
      </Card>

      <Card title="Agent recommendations">
        <List
          dataSource={data.insights}
          renderItem={(item, index) => (
            <List.Item>
              <Space>
                <Tag color="blue">Insight {index + 1}</Tag>
                <Text>{item}</Text>
              </Space>
            </List.Item>
          )}
        />
      </Card>
    </Space>
  );
}
